### ISSUE TITLE
lpips seems broken - 

### ISSUE THREAD

**Issue by johndpope** [danielroich/PTI#29]
the latest version 0.1.4 seems to break things with missing layer

Traceback (most recent call last):
  File "scripts/notebook.py", line 63, in <module>
    model_id = run_PTI(use_wandb=False, use_multi_id_training=use_multi_id_training)
  File "/home/jp/Documents/gitWorkspace/PTI/scripts/run_pti.py", line 40, in run_PTI
    coach = SingleIDCoach(dataloader, use_wandb)
  File "/home/jp/Documents/gitWorkspace/PTI/training/coaches/single_id_coach.py", line 13, in __init__
    super().__init__(data_loader, use_wandb)
  File "/home/jp/Documents/gitWorkspace/PTI/training/coaches/base_coach.py", line 36, in __init__
    self.lpips_loss = LPIPS(net=hyperparameters.lpips_type, lpips_layers=hyperparameters.pt_lpips_layers).to(global_config.device).eval()
TypeError: __init__() got an unexpected keyword argument 'lpips_layers'

I'd submit a PR - but my branch has drifted considerably.

**Comment by johndpope** [comment]
wait a sec 0.1.2 has issues too.

(torch) ➜  PTI git:(main) ✗ python scripts/notebook.py
Traceback (most recent call last):
  File "scripts/notebook.py", line 16, in <module>
    from scripts.run_pti import run_PTI
  File "/home/jp/Documents/gitWorkspace/PTI/scripts/run_pti.py", line 9, in <module>
    from training.coaches.multi_id_coach import MultiIDCoach
  File "/home/jp/Documents/gitWorkspace/PTI/training/coaches/multi_id_coach.py", line 7, in <module>
    from training.coaches.base_coach import BaseCoach
  File "/home/jp/Documents/gitWorkspace/PTI/training/coaches/base_coach.py", line 9, in <module>
    from lpips import LPIPS
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/lpips/__init__.py", line 7, in <module>
    from skimage.measure import compare_ssim
ImportError: cannot import name 'compare_ssim' from 'skimage.measure' (/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/skimage/measure/__init__.py)

**Comment by johndpope** [comment]
sorry merged a faulty branch.
